/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZahlungenRouteImport } from './routes/zahlungen'
import { Route as WechselRouteImport } from './routes/wechsel'
import { Route as StartRouteImport } from './routes/start'
import { Route as PruefenRouteImport } from './routes/pruefen'
import { Route as MitarbeiterRouteImport } from './routes/mitarbeiter'
import { Route as FertigRouteImport } from './routes/fertig'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AltesKontoRouteImport } from './routes/altes-konto'
import { Route as IndexRouteImport } from './routes/index'

const ZahlungenRoute = ZahlungenRouteImport.update({
  id: '/zahlungen',
  path: '/zahlungen',
  getParentRoute: () => rootRouteImport,
} as any)
const WechselRoute = WechselRouteImport.update({
  id: '/wechsel',
  path: '/wechsel',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefenRoute = PruefenRouteImport.update({
  id: '/pruefen',
  path: '/pruefen',
  getParentRoute: () => rootRouteImport,
} as any)
const MitarbeiterRoute = MitarbeiterRouteImport.update({
  id: '/mitarbeiter',
  path: '/mitarbeiter',
  getParentRoute: () => rootRouteImport,
} as any)
const FertigRoute = FertigRouteImport.update({
  id: '/fertig',
  path: '/fertig',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AltesKontoRoute = AltesKontoRouteImport.update({
  id: '/altes-konto',
  path: '/altes-konto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/altes-konto': typeof AltesKontoRoute
  '/dashboard': typeof DashboardRoute
  '/fertig': typeof FertigRoute
  '/mitarbeiter': typeof MitarbeiterRoute
  '/pruefen': typeof PruefenRoute
  '/start': typeof StartRoute
  '/wechsel': typeof WechselRoute
  '/zahlungen': typeof ZahlungenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/altes-konto': typeof AltesKontoRoute
  '/dashboard': typeof DashboardRoute
  '/fertig': typeof FertigRoute
  '/mitarbeiter': typeof MitarbeiterRoute
  '/pruefen': typeof PruefenRoute
  '/start': typeof StartRoute
  '/wechsel': typeof WechselRoute
  '/zahlungen': typeof ZahlungenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/altes-konto': typeof AltesKontoRoute
  '/dashboard': typeof DashboardRoute
  '/fertig': typeof FertigRoute
  '/mitarbeiter': typeof MitarbeiterRoute
  '/pruefen': typeof PruefenRoute
  '/start': typeof StartRoute
  '/wechsel': typeof WechselRoute
  '/zahlungen': typeof ZahlungenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/altes-konto'
    | '/dashboard'
    | '/fertig'
    | '/mitarbeiter'
    | '/pruefen'
    | '/start'
    | '/wechsel'
    | '/zahlungen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/altes-konto'
    | '/dashboard'
    | '/fertig'
    | '/mitarbeiter'
    | '/pruefen'
    | '/start'
    | '/wechsel'
    | '/zahlungen'
  id:
    | '__root__'
    | '/'
    | '/altes-konto'
    | '/dashboard'
    | '/fertig'
    | '/mitarbeiter'
    | '/pruefen'
    | '/start'
    | '/wechsel'
    | '/zahlungen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AltesKontoRoute: typeof AltesKontoRoute
  DashboardRoute: typeof DashboardRoute
  FertigRoute: typeof FertigRoute
  MitarbeiterRoute: typeof MitarbeiterRoute
  PruefenRoute: typeof PruefenRoute
  StartRoute: typeof StartRoute
  WechselRoute: typeof WechselRoute
  ZahlungenRoute: typeof ZahlungenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zahlungen': {
      id: '/zahlungen'
      path: '/zahlungen'
      fullPath: '/zahlungen'
      preLoaderRoute: typeof ZahlungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wechsel': {
      id: '/wechsel'
      path: '/wechsel'
      fullPath: '/wechsel'
      preLoaderRoute: typeof WechselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefen': {
      id: '/pruefen'
      path: '/pruefen'
      fullPath: '/pruefen'
      preLoaderRoute: typeof PruefenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitarbeiter': {
      id: '/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/mitarbeiter'
      preLoaderRoute: typeof MitarbeiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertig': {
      id: '/fertig'
      path: '/fertig'
      fullPath: '/fertig'
      preLoaderRoute: typeof FertigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/altes-konto': {
      id: '/altes-konto'
      path: '/altes-konto'
      fullPath: '/altes-konto'
      preLoaderRoute: typeof AltesKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AltesKontoRoute: AltesKontoRoute,
  DashboardRoute: DashboardRoute,
  FertigRoute: FertigRoute,
  MitarbeiterRoute: MitarbeiterRoute,
  PruefenRoute: PruefenRoute,
  StartRoute: StartRoute,
  WechselRoute: WechselRoute,
  ZahlungenRoute: ZahlungenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
